repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.278
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
    - id: mypy